#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-json-c-soname4
Version  : 0.13.1
Release  : 17
URL      : https://s3.amazonaws.com/json-c_releases/releases/json-c-0.13.1.tar.gz
Source0  : https://s3.amazonaws.com/json-c_releases/releases/json-c-0.13.1.tar.gz
Summary  : A JSON implementation in C
Group    : Development/Tools
License  : MIT
Requires: compat-json-c-soname4-lib = %{version}-%{release}
Requires: compat-json-c-soname4-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
Patch1: CVE-2020-12762.patch

%description


%package lib
Summary: lib components for the compat-json-c-soname4 package.
Group: Libraries
Requires: compat-json-c-soname4-license = %{version}-%{release}

%description lib
lib components for the compat-json-c-soname4 package.


%package lib32
Summary: lib32 components for the compat-json-c-soname4 package.
Group: Default
Requires: compat-json-c-soname4-license = %{version}-%{release}

%description lib32
lib32 components for the compat-json-c-soname4 package.


%package license
Summary: license components for the compat-json-c-soname4 package.
Group: Default

%description license
license components for the compat-json-c-soname4 package.


%prep
%setup -q -n json-c-0.13.1
cd %{_builddir}/json-c-0.13.1
%patch1 -p1
pushd ..
cp -a json-c-0.13.1 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644260055
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1644260055
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-json-c-soname4
cp %{_builddir}/json-c-0.13.1/COPYING %{buildroot}/usr/share/package-licenses/compat-json-c-soname4/0cd23537e3c32497c7b87157b36f9d2eb5fca64b
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/include/json-c/arraylist.h
rm -f %{buildroot}*/usr/include/json-c/bits.h
rm -f %{buildroot}*/usr/include/json-c/debug.h
rm -f %{buildroot}*/usr/include/json-c/json.h
rm -f %{buildroot}*/usr/include/json-c/json_c_version.h
rm -f %{buildroot}*/usr/include/json-c/json_config.h
rm -f %{buildroot}*/usr/include/json-c/json_inttypes.h
rm -f %{buildroot}*/usr/include/json-c/json_object.h
rm -f %{buildroot}*/usr/include/json-c/json_object_iterator.h
rm -f %{buildroot}*/usr/include/json-c/json_pointer.h
rm -f %{buildroot}*/usr/include/json-c/json_tokener.h
rm -f %{buildroot}*/usr/include/json-c/json_util.h
rm -f %{buildroot}*/usr/include/json-c/json_visit.h
rm -f %{buildroot}*/usr/include/json-c/linkhash.h
rm -f %{buildroot}*/usr/include/json-c/printbuf.h
rm -f %{buildroot}*/usr/lib32/libjson-c.so
rm -f %{buildroot}*/usr/lib32/pkgconfig/32json-c.pc
rm -f %{buildroot}*/usr/lib32/pkgconfig/json-c.pc
rm -f %{buildroot}*/usr/lib64/libjson-c.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/json-c.pc

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libjson-c.so.4
/usr/lib64/libjson-c.so.4.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libjson-c.so.4
/usr/lib32/libjson-c.so.4.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-json-c-soname4/0cd23537e3c32497c7b87157b36f9d2eb5fca64b
